<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Lambda</string>
  <key>uuid</key>
  <string>2F578C31-C4D5-4AE3-B16D-251673CE3D77</string>
  <key>scopeName</key>
  <string>source.lambda</string>
  <key>fileTypes</key>
  <array>
    <string>lam</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#declarations</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#patterns</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#constructors</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#types</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#literals</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#expressions</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keywords</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#operators</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#punctuation</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>declarations</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.declaration.data.lambda</string>
          <key>begin</key>
          <string>\b(data)\s+([A-Za-z][A-Za-z0-9_]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.data.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=^\s*(?:let|type|data)\b|\z)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#type-parameters</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#patterns</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.declaration.function.main.lambda</string>
          <key>begin</key>
          <string>\b(let)\s+(?:(rec)\s+)?(main)(?=\s*\(\s*\)\s*:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.let.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.recursive.lambda</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.main.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?==)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#value-parameters</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.declaration.function.lambda</string>
          <key>begin</key>
          <string>\b(let)\s+(?:(rec)\s+)?([A-Za-z][A-Za-z0-9_]*)(?=\s*(?:\[\s*[A-Za-z][A-Za-z0-9_]*\s*\]\s*)*\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.let.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.recursive.lambda</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?==)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#type-parameters</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#value-parameters</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.declaration.value.lambda</string>
          <key>begin</key>
          <string>\b(let)\s+(?:(rec)\s+)?([A-Za-z][A-Za-z0-9_]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.let.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.recursive.lambda</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.definition.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?==)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#type-parameters</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.declaration.type.lambda</string>
          <key>begin</key>
          <string>\b(type)\s+([A-Za-z][A-Za-z0-9_]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.type.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?==)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#type-parameters</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>expressions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.match.lambda</string>
          <key>match</key>
          <string>\b(match)\b|\b(with)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.match.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.match.with.lambda</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#patterns</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#constructors</string>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.abstraction.value.lambda</string>
          <key>match</key>
          <string>(λ)\s*([A-Za-z][A-Za-z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.lambda.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.abstraction.type.lambda</string>
          <key>match</key>
          <string>(Λ)\s*([A-Za-z][A-Za-z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.lambda.type.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.quantifier.forall.lambda</string>
          <key>match</key>
          <string>(∀)\s*([A-Za-z][A-Za-z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.quantifier.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.foreign.lambda</string>
          <key>begin</key>
          <string>\b(foreign)(?=\s*\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.foreign.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?&lt;=\])\s*([A-Za-z][A-Za-z0-9_]*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.external.lambda</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.function.lambda</string>
          <key>match</key>
          <string>\b(?!(?:if|then|else|let|rec|type|data|in|match|with|foreign|true|false)\b)[a-z][A-Za-z0-9_]*\b(?=\s*(?:\[|\())</string>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.other.lambda</string>
          <key>match</key>
          <string>\b(?!(?:if|then|else|let|rec|type|data|in|match|with|foreign|true|false)\b)[a-z][A-Za-z0-9_]*\b</string>
        </dict>
      </array>
    </dict>
    <key>patterns</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.pattern.constructor.lambda</string>
          <key>match</key>
          <string>(\|)\s*([A-Za-z][A-Za-z0-9_]*)(?=\s*(?:\(|-&gt;|$))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.pattern.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.constructor.lambda</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <key>constructors</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>entity.name.function.constructor.lambda</string>
          <key>match</key>
          <string>\b[A-Z][A-Za-z0-9_]*\b(?=\s*(?:\[|\())</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.language.constructor.lambda</string>
          <key>match</key>
          <string>\b[A-Z][A-Za-z0-9_]*\b</string>
        </dict>
      </array>
    </dict>
    <key>type-parameters</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.type-parameter.lambda</string>
          <key>match</key>
          <string>(\[)\s*([A-Za-z][A-Za-z0-9_]*)\s*(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.type-parameter.begin.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.type-parameter.end.lambda</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <key>value-parameters</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>meta.parameter.value.lambda</string>
          <key>begin</key>
          <string>(\()\s*([A-Za-z][A-Za-z0-9_]*)(\s*:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.parameters.begin.lambda</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.type-annotation.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\)</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.parameters.end.lambda</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#punctuation</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.parameter.unit.lambda</string>
          <key>match</key>
          <string>\(\s*\)</string>
        </dict>
      </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>storage.type.primitive.lambda</string>
          <key>match</key>
          <string>\b(?:i8|i16|i32|i64|u8|u16|u32|u64|f32|f64|isize|usize|char|bool|unit|foreign\.C\.(?:String|VoidPtr|Ptr))\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.class</string>
          <key>match</key>
          <string>\b[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)*\b(?=\s*\[)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.parameter</string>
          <key>match</key>
          <string>\b[A-Z]\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.class</string>
          <key>match</key>
          <string>\b[A-Z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)*\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.type.arrow.lambda</string>
          <key>match</key>
          <string>→</string>
        </dict>
      </array>
    </dict>
    <key>literals</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.language.boolean.lambda</string>
          <key>match</key>
          <string>\b(?:true|false)\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.float.lambda</string>
          <key>match</key>
          <string>\b[0-9]+\.[0-9]+(?:[eE][+-]?[0-9]+)?(?:f32|f64)?\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.integer.lambda</string>
          <key>match</key>
          <string>\b[0-9]+(?:i8|i16|i32|i64|isize|u8|u16|u32|u64|usize)?\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>string.quoted.double.lambda</string>
          <key>begin</key>
          <string>"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>"</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.lambda</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>constant.character.escape.lambda</string>
              <key>match</key>
              <string>\\(?:[\\'"nrt0]|[0-7]{3})</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>string.quoted.single.character.lambda</string>
          <key>begin</key>
          <string>'</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.character.begin.lambda</string>
            </dict>
          </dict>
          <key>end</key>
          <string>'</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.character.end.lambda</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>constant.character.literal.lambda</string>
              <key>match</key>
              <string>[A-Za-z]</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>keyword.control.conditional.if.lambda</string>
          <key>match</key>
          <string>\bif\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.conditional.then.lambda</string>
          <key>match</key>
          <string>\bthen\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.conditional.else.lambda</string>
          <key>match</key>
          <string>\belse\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.declaration.lambda</string>
          <key>match</key>
          <string>\b(?:let|rec|type|data)\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.match.lambda</string>
          <key>match</key>
          <string>\bmatch\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.match.with.lambda</string>
          <key>match</key>
          <string>\bwith\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.in.lambda</string>
          <key>match</key>
          <string>\bin\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.other.foreign.lambda</string>
          <key>match</key>
          <string>\bforeign\b</string>
        </dict>
      </array>
    </dict>
    <key>operators</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>keyword.operator.comparison.lambda</string>
          <key>match</key>
          <string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.match.arrow.lambda</string>
          <key>match</key>
          <string>-&gt;</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.arithmetic.lambda</string>
          <key>match</key>
          <string>[+\-*/]</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.logical.lambda</string>
          <key>match</key>
          <string>!</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.assignment.lambda</string>
          <key>match</key>
          <string>=</string>
        </dict>
      </array>
    </dict>
    <key>punctuation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>punctuation.separator.type-annotation.lambda</string>
          <key>match</key>
          <string>:</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.terminator.expression.lambda</string>
          <key>match</key>
          <string>;</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.separator.sequence.lambda</string>
          <key>match</key>
          <string>\.</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters.begin.lambda</string>
          <key>match</key>
          <string>\(</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters.end.lambda</string>
          <key>match</key>
          <string>\)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.definition.type-parameter.begin.lambda</string>
          <key>match</key>
          <string>\[</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.definition.type-parameter.end.lambda</string>
          <key>match</key>
          <string>\]</string>
        </dict>
      </array>
    </dict>
  </dict>
</dict>
</plist>
